### ISSUE TITLE
Feature Request - whitelist directories to monitor

### ISSUE THREAD

**Issue by peterhoeg** [mkcms/maildirwatch#4]
Instead of having the option to `ignore` unwanted directories, it would be great to be able to simply include the ones that I do want monitored.

My usecase is basically that unless it's in my inbox I don't care about it, so that means a whole lot of ignoring.

**Comment by mkcms** [comment]
Hi, I will consider it (PR welcome), in the meantime:

> My usecase is basically that unless it's in my inbox I don't care about it

It's not mentioned in the README, but if you only want to watch a single directory inside your Maildir, you can just point the `maildir` configuration option to that directory, e.g. if you have a Maildir like this:

```
/home/user/Maildir
  |- Inbox
  |- Spam
  |- Sent
  |- Archive
```

and you only want to watch `Inbox`, you can set `maildir` config option to `/home/user/Maildir/Inbox`.

EDIT: The above will only work if you don't have any "sub-maildirs" in `Inbox`, otherwise they'd be watched too.

**Comment by peterhoeg** [comment]
>   It's not mentioned in the README, but if you only want to watch a single
>   directory inside your Maildir, you can just point the maildir
>   configuration option to that, e.g. if you have a Maildir like this:

Apologies for not making that clear - I have multiple accounts and I only want the inbox in each account.

**Comment by mkcms** [comment]
I just pushed bc8c1435ff3e8a6bd28dc60d6982c33ae9c915be to master. Can you check?

**Comment by peterhoeg** [comment]
In my case I had to use `whitelist = **/inbox` but this works, excellent, thanks.
